<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KategorisSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('kategoris')->truncate();

        DB::table('kategoris')->insert([
        [
            'id' => 1,
            'nama' => 'MOBILE LEGENDS',
            'sub_nama' => 'Moonton',
            'kode' => 'mobile-legends',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/01KGEV3B6ENK2W076EDWHXQ9YG.webp',
            'banner' => 'assets/banner_game/01KGEV3B8N33RAJW37ASK8EM8K.webp',
            'tipe' => 'populer',
            'server_id' => 1,
            'deskripsi_game' => '<p>&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID &amp;amp; Server&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;</p>',
            'deskripsi_field' => '<p>Contoh : 727383 &amp;amp; 7282</p>',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:14:56',
            'updated_at' => '2026-02-02 10:32:16'
        ],
        [
            'id' => 2,
            'nama' => 'FREE FIRE',
            'sub_nama' => 'Garena',
            'kode' => 'free-fire',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/01KGEVK762VDMPQXKXRZ3VPWFE.webp',
            'banner' => 'assets/banner_game/01KGEVK77T8J8Q2CEGR5K8JXZ5.webp',
            'tipe' => 'populer',
            'server_id' => null,
            'deskripsi_game' => '<p>&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&amp;nbsp;&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;</p>',
            'deskripsi_field' => '<p>Contoh : 72828283</p>',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:15:46',
            'updated_at' => '2026-02-02 10:40:29'
        ],
        [
            'id' => 3,
            'nama' => 'Genshin Impact',
            'sub_nama' => 'HoYoverse',
            'kode' => 'genshin-impact',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/01KGF53Z7D1ZTWJHEKEAA0K0HQ.webp',
            'banner' => 'assets/banner_game/01KGF53Z7NCH4N395AF3GKQ41Q.webp',
            'tipe' => 'populer',
            'server_id' => null,
            'deskripsi_game' => '<p>&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID &amp;amp; Server&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;</p>',
            'deskripsi_field' => '<p>Contoh : 8282838 &amp; Asia</p>',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:17:51',
            'updated_at' => '2026-02-02 13:26:55'
        ],
        [
            'id' => 4,
            'nama' => 'PUBG MOBILE',
            'sub_nama' => 'Tencent Games',
            'kode' => 'pubg-mobile',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/71e8b7b803ff7b54b582ed66fd50fe28fafc8bb6.webp',
            'banner' => 'assets/banner_game/71e8b7b803ff7b54b582ed66fd50fe28fafc8bb6.webp',
            'tipe' => 'populer',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 8292827',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:19:05',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 5,
            'nama' => 'Honor Of Kings',
            'sub_nama' => 'Tencent Games',
            'kode' => 'honor-of-kings',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/c663f0b4e66b14e1ac02582c6e5938dc82074f3c.jpg',
            'banner' => 'assets/banner_game/c663f0b4e66b14e1ac02582c6e5938dc82074f3c.jpg',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 718393837',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:22:23',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 7,
            'nama' => 'Call Of Duty MOBILE',
            'sub_nama' => 'Garena',
            'kode' => 'call-of-duty-mobile',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/COD-ezgif.webp',
            'banner' => 'assets/banner_game/COD-ezgif.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 817262737',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:27:16',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 8,
            'nama' => 'POINT BLANK',
            'sub_nama' => 'Zepetto',
            'kode' => 'point-blank',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/Pebe-ezgif.webp',
            'banner' => 'assets/banner_game/Pebe-ezgif.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 82929298',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:28:57',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 9,
            'nama' => 'Valorant',
            'sub_nama' => 'Riot Games',
            'kode' => 'valorant',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/Valorant-ezgif.webp',
            'banner' => 'assets/banner_game/Valorant-ezgif.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '<p>&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&amp;nbsp;&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;</p>',
            'deskripsi_field' => '<p>Contoh : 18283737#WeJizy</p>',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:35:05',
            'updated_at' => '2026-02-02 13:48:19'
        ],
        [
            'id' => 10,
            'nama' => 'Magic Chess',
            'sub_nama' => 'Vizta Games',
            'kode' => 'magic-chess',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/mcgogo.webp',
            'banner' => 'assets/banner_game/mcgogo.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID &amp;amp; Server&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 7173737 &amp; 7272',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:37:04',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 11,
            'nama' => 'Honkai Star Rail',
            'sub_nama' => 'Mihoyo',
            'kode' => 'honkai-star-rail',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/381dcc003bce07270007a90299547992122554c4.webp',
            'banner' => 'assets/banner_game/381dcc003bce07270007a90299547992122554c4.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID &amp;amp; Pilih Server&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 2738383 &amp; Asia',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:39:49',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 12,
            'nama' => 'Honkai Impact 3',
            'sub_nama' => 'MiHoyo',
            'kode' => 'honkai-impact-3',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/8ef67af01dcfe539a69f544fc724372ab5980cb5.webp',
            'banner' => 'assets/banner_game/8ef67af01dcfe539a69f544fc724372ab5980cb5.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&amp;nbsp;&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 717288482',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:43:08',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 13,
            'nama' => 'Undawn',
            'sub_nama' => 'Garena',
            'kode' => 'undawn',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/8ae36cee3ea060c729ce70355055beafd3011db5.webp',
            'banner' => 'assets/banner_game/8ae36cee3ea060c729ce70355055beafd3011db5.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&amp;nbsp;&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 8282838',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:44:23',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 14,
            'nama' => 'Eggy Party',
            'sub_nama' => 'NetEase Games',
            'kode' => 'eggy-party',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/eggpart (1).webp',
            'banner' => 'assets/banner_game/eggpart (1).webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID &amp;amp; Server&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 7272838283 &amp; 7282',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:47:16',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 15,
            'nama' => 'FC Mobile',
            'sub_nama' => 'EA Sports',
            'kode' => 'fc-mobile',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/980a5358bf1e9ccacb0cfaa460d63aa15bc0d541.webp',
            'banner' => 'assets/banner_game/980a5358bf1e9ccacb0cfaa460d63aa15bc0d541.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&amp;nbsp;&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 8283838',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:49:47',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 16,
            'nama' => 'Sausage Man',
            'sub_nama' => 'X. D. Network',
            'kode' => 'sausage-man',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/074b6ef5f339c6c8ba74b9ec1d298cfc1efa4988.jpeg',
            'banner' => 'assets/banner_game/074b6ef5f339c6c8ba74b9ec1d298cfc1efa4988.jpeg',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&amp;nbsp;&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 8283838',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:50:50',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 17,
            'nama' => 'JOKI RANK ECER',
            'sub_nama' => 'Sweg.JK',
            'kode' => 'joki-rank-ecer',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/9dc8550f5626f4a669f1ce4b13168da4bacd5e94.webp',
            'banner' => 'assets/banner_game/9dc8550f5626f4a669f1ce4b13168da4bacd5e94.webp',
            'tipe' => 'joki',
            'server_id' => null,
            'deskripsi_game' => '',
            'deskripsi_field' => 'Harap Matikan Verifikasi 2 Langkah',
            'category_type_id' => 2,
            'created_at' => '2025-04-21 22:52:10',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 18,
            'nama' => 'Mlbb Via Login',
            'sub_nama' => 'Via Login',
            'kode' => 'mlbb-vilog',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/e350bb2275777da25f912e020ed61a99956a30ca.webp',
            'banner' => 'assets/banner_game/e350bb2275777da25f912e020ed61a99956a30ca.webp',
            'tipe' => 'vilogml',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Data&amp;nbsp;&lt;/li&gt;&lt;li&gt;Harap Tanyakan Admin Untuk Ketersediaan Terlebih Dahulu&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Pesanan Diproses Manual 1-3 Jam Oleh Admin&lt;/li&gt;&lt;li&gt;Akun Akan Dimainkan Rank 1-3 Match&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Harap Matikan Verifikasi 2 Langkah',
            'category_type_id' => 2,
            'created_at' => '2025-04-21 22:55:34',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 19,
            'nama' => 'ARENA OF VALOR',
            'sub_nama' => 'Garena',
            'kode' => 'arena-of-valor',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/174055350b162cde732304df46abb92beb6bbcf4.webp',
            'banner' => 'assets/banner_game/174055350b162cde732304df46abb92beb6bbcf4.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID&amp;nbsp;&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 828273',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 22:58:05',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 20,
            'nama' => 'Identity V',
            'sub_nama' => 'NetEase',
            'kode' => 'identity-v',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/identity_v-47b9-original.webp',
            'banner' => 'assets/banner_game/identity_v-47b9-original.webp',
            'tipe' => 'game',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Topup :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan ID &amp;amp; Pilih Server&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 828374748 &amp; Asia',
            'category_type_id' => 1,
            'created_at' => '2025-04-21 23:02:02',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 21,
            'nama' => 'Alight Motion',
            'sub_nama' => 'Akun Premium',
            'kode' => 'alight-motion-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/alight-motion.webp',
            'banner' => 'assets/banner_game/alight-motion.webp',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Nomor&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 0822xxxxx',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:06:13',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 22,
            'nama' => 'Amazon Prime Video',
            'sub_nama' => 'Akun Premium',
            'kode' => 'amazon-prime-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/primevideo-icon.png',
            'banner' => 'assets/banner_game/primevideo-icon.png',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:09:43',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 23,
            'nama' => 'Bstation Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'bstation-premium-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/bstation.webp',
            'banner' => 'assets/banner_game/bstation.webp',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:18:13',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 24,
            'nama' => 'Canva Pro',
            'sub_nama' => 'Akun Premium',
            'kode' => 'canva-pro-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/eb6e9b42a3ee41f31451c7bc6d29e86e.jpg_720x720q80.jpg_.webp',
            'banner' => 'assets/banner_game/eb6e9b42a3ee41f31451c7bc6d29e86e.jpg_720x720q80.jpg_.webp',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:19:29',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 25,
            'nama' => 'Capcut Pro',
            'sub_nama' => 'Akun Premium',
            'kode' => 'capcut-pro-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/capcut-logo.jpg',
            'banner' => 'assets/banner_game/capcut-logo.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:20:19',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 26,
            'nama' => 'Disney Hotstar',
            'sub_nama' => 'Akun Premium',
            'kode' => 'disney-hotstar-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/disney-hotstar-icon.jpg',
            'banner' => 'assets/banner_game/disney-hotstar-icon.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:21:27',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 27,
            'nama' => 'Getcontact Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'Getcontact-premium-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/get-contact.png',
            'banner' => 'assets/banner_game/get-contact.png',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Nomor &amp;amp; Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : 0822xxxx &amp; email@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:24:53',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 28,
            'nama' => 'iQIYI Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'iqiyi-premium-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/iqiyi-icon.webp',
            'banner' => 'assets/banner_game/iqiyi-icon.webp',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:26:22',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 29,
            'nama' => 'Netflix Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'netflix-premium-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/netflix.jpg',
            'banner' => 'assets/banner_game/netflix.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:27:38',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 30,
            'nama' => 'Spotify Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'spotify-premium-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/spotify.jpg',
            'banner' => 'assets/banner_game/spotify.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:28:40',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 31,
            'nama' => 'Youtube Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'youtube-premium',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/youtube-new.jpg',
            'banner' => 'assets/banner_game/youtube-new.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:29:37',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 32,
            'nama' => 'Vidio Premier',
            'sub_nama' => 'Akun Premium',
            'kode' => 'vidio-premier-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/vidio-premier.jpg',
            'banner' => 'assets/banner_game/vidio-premier.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:31:04',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 33,
            'nama' => 'TikTok Music',
            'sub_nama' => 'Akun Premium',
            'kode' => 'tiktok-music-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/tiktok-music.jpg',
            'banner' => 'assets/banner_game/tiktok-music.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:32:21',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 34,
            'nama' => 'Viu Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'viu-premium-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/viu-icon.jpg',
            'banner' => 'assets/banner_game/viu-icon.jpg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:33:20',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 35,
            'nama' => 'WeTv Premium',
            'sub_nama' => 'Akun Premium',
            'kode' => 'wetv-premium-vip',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/bcc57869475b868a686844e4fb82e4ee.jpeg',
            'banner' => 'assets/banner_game/bcc57869475b868a686844e4fb82e4ee.jpeg',
            'tipe' => 'app',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Pembelian :&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan Email&lt;/li&gt;&lt;li&gt;Pilih nominal&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Tulis kode promo (Jika ada)&lt;/li&gt;&lt;li&gt;Masukkan No. whatsapp&lt;/li&gt;&lt;li&gt;Klik pesan sekarang &amp;amp; lakukan pembayaran&lt;/li&gt;&lt;li&gt;Selesai&lt;/li&gt;&lt;/ol&gt;',
            'deskripsi_field' => 'Contoh : wesintopup@gmail.com',
            'category_type_id' => 3,
            'created_at' => '2025-04-21 23:34:26',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 36,
            'nama' => 'XL',
            'sub_nama' => 'Paket Data XL',
            'kode' => 'pulsa-xl',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/xl.png',
            'banner' => 'assets/banner_game/xl.png',
            'tipe' => 'pulsa',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Order:&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan nomor XL anda&lt;/li&gt;&lt;li&gt;Pilih jumlah pulsa yang diinginkan&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Masukkan nomor whatsapp&lt;/li&gt;&lt;li&gt;Klik beli sekarang dan lakukan pembayaran&lt;/li&gt;&lt;li&gt;Pulsa akan masuk otomatis&lt;/li&gt;&lt;/ol&gt;&lt;p&gt;Informasi&lt;br&gt;Harap periksa kembali nomor anda&lt;br&gt;Kesalahan penulisan nomor mutlak tanggung jawab anda sebagai pembeli&lt;/p&gt;',
            'deskripsi_field' => 'Masukan Nomor Kamu Contoh: 0857********',
            'category_type_id' => 4,
            'created_at' => '2025-05-02 11:07:01',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 37,
            'nama' => 'INDOSAT',
            'sub_nama' => 'Paket Data Indosat',
            'kode' => 'paket-indosat',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/indosat.png',
            'banner' => 'assets/banner_game/indosat.png',
            'tipe' => 'pulsa',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;Cara Order:&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Masukkan nomor Indosat anda&lt;/li&gt;&lt;li&gt;Pilih jumlah pulsa yang diinginkan&lt;/li&gt;&lt;li&gt;Pilih metode pembayaran&lt;/li&gt;&lt;li&gt;Masukkan nomor whatsapp&lt;/li&gt;&lt;li&gt;Klik beli sekarang dan lakukan pembayaran&lt;/li&gt;&lt;li&gt;Pulsa akan masuk otomatis&lt;/li&gt;&lt;/ol&gt;&lt;p&gt;Informasi&lt;br&gt;Harap periksa kembali nomor anda&lt;br&gt;Kesalahan penulisan nomor mutlak tanggung jawab anda sebagai pembeli&lt;/p&gt;',
            'deskripsi_field' => '0857*******',
            'category_type_id' => 4,
            'created_at' => '2025-05-02 11:17:16',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 38,
            'nama' => 'TELKOMSEL',
            'sub_nama' => 'pulsa telkomsel',
            'kode' => 'pulsa-telkomsel',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/logo-telkomsel.webp',
            'banner' => 'assets/banner_game/logo-telkomsel.webp',
            'tipe' => 'pulsa',
            'server_id' => null,
            'deskripsi_game' => '&lt;h3&gt;🔥 PAKET PULSA TELKOMSEL MURAH &amp;amp; CEPAT! 🔥&lt;/h3&gt;&lt;p&gt;&lt;strong&gt;Top Up Pulsa Telkomsel Anti Ribet &amp;amp; Langsung Masuk!&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;🔹 Tersedia nominal:&lt;br&gt;– 5.000 | 10.000 | 15.000 | 20.000 | 25.000 | 50.000 | 100.000&lt;br&gt;🔹 Harga bersaing &amp;amp; lebih murah dari konter!&lt;br&gt;🔹 Pulsa masuk dalam hitungan detik-menit&lt;br&gt;🔹 Cocok untuk isi ulang harian, emergency, atau hadiah teman&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Kelebihan beli di sini:&lt;/strong&gt;&lt;br&gt;✅ Fast respon &amp;amp; layanan ramah&lt;br&gt;✅ Bisa order 24 jam&lt;br&gt;✅ Aman &amp;amp; terpercaya&lt;br&gt;✅ Cocok untuk reseller&lt;/p&gt;&lt;p&gt;🛒 &lt;i&gt;Langsung order sekarang dan rasakan layanan cepat &amp;amp; terpercaya dari kami!&lt;/i&gt;&lt;/p&gt;',
            'deskripsi_field' => '082189093929',
            'category_type_id' => 4,
            'created_at' => '2025-05-08 14:17:37',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        [
            'id' => 39,
            'nama' => 'ROBLOX',
            'sub_nama' => 'Roblox Corporation',
            'kode' => '12345678',
            'status' => 'active',
            'thumbnail' => 'assets/thumbnail/990127e0fef488963ad7273041618b7ce099a3ee.png',
            'banner' => 'assets/banner_game/c57a819ba0f3587ce92c372df48a3fe7df761c78.png',
            'tipe' => 'populer',
            'server_id' => null,
            'deskripsi_game' => '&lt;p&gt;&lt;strong&gt;Top Up Robux? Di Sini Aja!&lt;/strong&gt;&lt;br&gt;Mau beli Robux cepet, murah, dan gak ribet? Di sini tempatnya! Cukup masukin username kamu, pilih jumlah Robux, bayar, dan duduk manis — Robux langsung meluncur ke akunmu!&lt;/p&gt;&lt;p&gt;💸 Murah meriah&lt;br&gt;⚡ Super cepat&lt;br&gt;🔒 Aman dan terpercaya&lt;br&gt;📱 Bayar pake e-wallet, pulsa, atau transfer bank&lt;/p&gt;&lt;p&gt;Main Roblox makin seru kalau Robux kamu banyak! Yuk top up sekarang di [Nama Web Kamu]&lt;/p&gt;',
            'deskripsi_field' => 'ID : 1234567',
            'category_type_id' => 1,
            'created_at' => '2025-09-04 03:46:12',
            'updated_at' => '2026-01-16 05:25:09'
        ],
        ]);
    }
}