<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;

class UsersSeeder extends Seeder
{
    public function run(): void
    {
        $foreignKeysWereEnabled = $this->foreignKeyChecksEnabled();

        Schema::disableForeignKeyConstraints();

        try {
            DB::table('users')->truncate();
        } finally {
            if ($foreignKeysWereEnabled) {
                Schema::enableForeignKeyConstraints();
            }
        }

        DB::table('users')->insert([
        [
            'id' => 312,
            'name' => 'egymaulana',
            'username' => 'egymaulana',
            'referral_code' => 'REF-6X6GY1',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user1@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000312',
            'balance' => 40499,
            'role' => 'Admin',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-04-20 02:32:53',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 313,
            'name' => 'merchant',
            'username' => 'tripay',
            'referral_code' => 'REF-HCLKWR',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user2@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000313',
            'balance' => 0,
            'role' => 'Admin',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-04-29 09:48:55',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 314,
            'name' => 'Egy',
            'username' => 'egy014',
            'referral_code' => 'REF-OTVPXF',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user3@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000314',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-02 12:26:12',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 315,
            'name' => 'ardera',
            'username' => 'deraganteng',
            'referral_code' => 'REF-Y3EWHD',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user4@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000315',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-05 14:26:04',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 316,
            'name' => 'Rafff',
            'username' => 'Rafzz19999',
            'referral_code' => 'REF-RKTS8Q',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user5@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000316',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-06 02:01:03',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 317,
            'name' => 'Rizky aditya',
            'username' => 'riskii',
            'referral_code' => 'REF-WVFWHQ',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user6@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000317',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-06 04:46:05',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 318,
            'name' => 'ardian',
            'username' => 'iyanzz',
            'referral_code' => 'REF-0P9NPK',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user7@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000318',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-06 07:34:31',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 319,
            'name' => 'Atha Al Fathir',
            'username' => 'Fathir',
            'referral_code' => 'REF-CB3HGM',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user8@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000319',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-06 08:10:24',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 320,
            'name' => 'hardiansyah',
            'username' => 'ardyy2221',
            'referral_code' => 'REF-JLG4WA',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user9@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000320',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-06 16:06:17',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 321,
            'name' => 'hardiansyah',
            'username' => 'ardyy123',
            'referral_code' => 'REF-ADGSLP',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user9@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000321',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-06 16:07:01',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 322,
            'name' => 'ojan',
            'username' => 'ojan321',
            'referral_code' => 'REF-FSWC2B',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user10@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000322',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-07 03:58:45',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 323,
            'name' => 'wawan',
            'username' => 'wawan123',
            'referral_code' => 'REF-JZWU3X',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user11@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000323',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-07 05:26:52',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 324,
            'name' => 'Opi',
            'username' => 'poa123',
            'referral_code' => 'REF-GOGALK',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user12@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000324',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-07 13:27:32',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 325,
            'name' => 'Tesaastore',
            'username' => 'Tecaa0105',
            'referral_code' => 'REF-IJYAOC',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user13@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000325',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-08 10:39:13',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 326,
            'name' => 'Tesaastore',
            'username' => 'Tesaamarket',
            'referral_code' => 'REF-U9QEJM',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user13@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000326',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-08 10:40:02',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 327,
            'name' => 'fiqqt',
            'username' => 'Muhammad afiq',
            'referral_code' => 'REF-WFRX6F',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user14@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000327',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-09 14:57:39',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 328,
            'name' => 'Muhammad Rizky Maulana',
            'username' => 'rizky97',
            'referral_code' => 'REF-DZXELA',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user15@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000328',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-12 15:46:19',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 329,
            'name' => 'Jef133',
            'username' => 'semzvak',
            'referral_code' => 'REF-7PMBVV',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user16@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000329',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-17 16:52:51',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 330,
            'name' => 'Khodhi urrohman',
            'username' => 'kodaii',
            'referral_code' => 'REF-NEK27R',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user17@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000330',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-17 18:12:59',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 331,
            'name' => 'farel',
            'username' => 'farell',
            'referral_code' => 'REF-YHG6HE',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user18@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000331',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-19 09:24:40',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 332,
            'name' => 'aditya',
            'username' => 'adityaa',
            'referral_code' => 'REF-OV03JE',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user19@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000332',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-20 18:00:57',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 333,
            'name' => 'Azka Himam',
            'username' => 'demonnico',
            'referral_code' => 'REF-7R4HBF',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user20@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000333',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-21 04:06:15',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 334,
            'name' => 'Jamil Mildani',
            'username' => 'Mildani',
            'referral_code' => 'REF-RET1F3',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user21@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000334',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-22 22:44:48',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 335,
            'name' => 'Zkaafahri',
            'username' => 'zkaareal19',
            'referral_code' => 'REF-QIJQVT',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user22@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000335',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-23 07:00:11',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 336,
            'name' => 'sigit alvina',
            'username' => 'vinnzz',
            'referral_code' => 'REF-2BBBGV',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user23@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000336',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-24 05:01:42',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 337,
            'name' => 'Adit Ariyadi',
            'username' => 'user24',
            'referral_code' => 'REF-IQWSDN',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user24@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000337',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-24 05:52:02',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 338,
            'name' => 'zulham',
            'username' => 'zulhamzul',
            'referral_code' => 'REF-DYCIFV',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user25@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000338',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-05-31 07:00:56',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 339,
            'name' => 'mat',
            'username' => 'matzero',
            'referral_code' => 'REF-CCXAS3',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user26@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000339',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-06-06 15:02:26',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 340,
            'name' => 'Matin Al Abbas N.S',
            'username' => 'BsshvN¡',
            'referral_code' => 'REF-QW7DXV',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user27@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000340',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-06-07 13:25:01',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 341,
            'name' => 'Rifai',
            'username' => 'empatlas',
            'referral_code' => 'REF-RPKXJX',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user28@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000341',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-06-08 13:50:26',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 342,
            'name' => 'arayyan',
            'username' => 'Rayan27',
            'referral_code' => 'REF-XEGW16',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user29@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000342',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-06-12 09:39:55',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 343,
            'name' => 'ADRIAN MULIA',
            'username' => 'FaldoStore',
            'referral_code' => 'REF-SZ1QP1',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user30@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000343',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-06-28 13:35:23',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 344,
            'name' => 'yudhaa',
            'username' => 'yudhaap23',
            'referral_code' => 'REF-AOOO49',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user31@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000344',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-07-04 07:30:29',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 345,
            'name' => 'Vinn',
            'username' => 'vinnprikitiw',
            'referral_code' => 'REF-IZL2CG',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user32@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000345',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-07-10 18:57:59',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 346,
            'name' => 'Supri Yanto',
            'username' => 'reza64',
            'referral_code' => 'REF-0GPEHM',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user33@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000346',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-08-08 15:57:26',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 347,
            'name' => 'Zaki kurnia ramadh',
            'username' => 'zaki Kurnia ramadhan',
            'referral_code' => 'REF-H1BDIN',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user34@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000347',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-08-21 00:47:51',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 348,
            'name' => 'Alfareza',
            'username' => 'Zareeee',
            'referral_code' => 'REF-8RLHAM',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user35@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000348',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-09-22 11:57:54',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 349,
            'name' => 'Super Admin',
            'username' => 'superadmin',
            'referral_code' => 'REF-P6DLAM',
            'uplink' => null,
            'password' => '\\.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'email' => 'user36@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000349',
            'balance' => 40000,
            'role' => 'Admin',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-04 11:02:14',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 350,
            'name' => 'superadmin',
            'username' => 'anonim',
            'referral_code' => 'REF-RZSF2K',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user37@example.com',
            'remember_token' => null,
            'no_wa' => null,
            'balance' => null,
            'role' => 'Admin',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-04 12:30:46',
            'updated_at' => '2026-02-17 19:26:03',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 351,
            'name' => 'Administrator',
            'username' => 'admin',
            'referral_code' => 'REF-TS0QEB',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'user38@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000351',
            'balance' => 1000000,
            'role' => 'Admin',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 352,
            'name' => 'Budi Platinum',
            'username' => 'budi_platinum',
            'referral_code' => 'REF-HOVJMW',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'budi.platinum@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000352',
            'balance' => 71320,
            'role' => 'Platinum',
            'affiliate_status' => 'rejected',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-20 16:03:14',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 353,
            'name' => 'Siti Platinum',
            'username' => 'siti_platinum',
            'referral_code' => 'REF-ZU3GEB',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'siti.platinum@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000353',
            'balance' => 750000,
            'role' => 'Platinum',
            'affiliate_status' => 'active',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-21 07:29:21',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 354,
            'name' => 'Andi Gold',
            'username' => 'andi_gold',
            'referral_code' => 'REF-3E1SB7',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'andi.gold@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000354',
            'balance' => 0,
            'role' => 'Gold',
            'affiliate_status' => 'active',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-21 07:57:09',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 355,
            'name' => 'Dewi Gold',
            'username' => 'dewi_gold',
            'referral_code' => 'REF-S1QPNU',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'dewi.gold@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000355',
            'balance' => 250000,
            'role' => 'Gold',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 356,
            'name' => 'Rizki Gold',
            'username' => 'rizki_gold',
            'referral_code' => 'REF-46M0A0',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'rizki.gold@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000356',
            'balance' => 313186,
            'role' => 'Gold',
            'affiliate_status' => 'active',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-23 09:38:32',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 357,
            'name' => 'Ahmad Member',
            'username' => 'ahmad_member',
            'referral_code' => 'REF-F7DNHV',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'ahmad.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000357',
            'balance' => 134000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 358,
            'name' => 'Rina Member',
            'username' => 'rina_member',
            'referral_code' => 'REF-SPKJRV',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'rina.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000358',
            'balance' => 125000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 359,
            'name' => 'Doni Member',
            'username' => 'doni_member',
            'referral_code' => 'REF-BUJHVG',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'doni.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000359',
            'balance' => 85000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 360,
            'name' => 'Lina Member',
            'username' => 'lina_member',
            'referral_code' => 'REF-7LA9ZG',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'lina.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000360',
            'balance' => 92000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:20',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 361,
            'name' => 'Yanto Member',
            'username' => 'yanto_member',
            'referral_code' => 'REF-KSJBOD',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'yanto.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000361',
            'balance' => 101000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:21',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 362,
            'name' => 'Sri Member',
            'username' => 'sri_member',
            'referral_code' => 'REF-WJJCCT',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'sri.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000362',
            'balance' => 187000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:21',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 363,
            'name' => 'Bambang Member',
            'username' => 'bambang_member',
            'referral_code' => 'REF-5GOJGA',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'bambang.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000363',
            'balance' => 86000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:21',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 364,
            'name' => 'Wati Member',
            'username' => 'wati_member',
            'referral_code' => 'REF-GP71AQ',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'wati.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000364',
            'balance' => 108000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:21',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 365,
            'name' => 'Joko Member',
            'username' => 'joko_member',
            'referral_code' => 'REF-0BYBN1',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'joko.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000365',
            'balance' => 58000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:21',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 366,
            'name' => 'Fitri Member',
            'username' => 'fitri_member',
            'referral_code' => 'REF-ISCOKK',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'fitri.member@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000366',
            'balance' => 181000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2025-10-16 05:03:21',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 367,
            'name' => 'Test Tier',
            'username' => 'test_tier_user',
            'referral_code' => 'REF-1RO297',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => 'test_tier@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000367',
            'balance' => 0,
            'role' => 'Platinum',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2026-02-09 15:49:04',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 368,
            'name' => 'Test Uplink',
            'username' => 'test_uplink',
            'referral_code' => 'REF-UPLINK',
            'uplink' => null,
            'password' => Hash::make('password'),
            'email' => '[REDACTED]',
            'remember_token' => null,
            'no_wa' => '6281000000368',
            'balance' => 2000,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2026-02-09 16:56:44',
            'updated_at' => '2026-02-09 16:58:03',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 369,
            'name' => 'Test Downlink',
            'username' => 'test_downlink',
            'referral_code' => 'REF-9PDP6E',
            'uplink' => 'test_uplink',
            'password' => Hash::make('password'),
            'email' => '[REDACTED]',
            'remember_token' => null,
            'no_wa' => '6281000000369',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2026-02-09 16:56:44',
            'updated_at' => '2026-02-16 12:26:13',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        [
            'id' => 370,
            'name' => 'ming',
            'username' => 'ming_ming',
            'referral_code' => 'REF-UOMKRZ',
            'uplink' => 'rizki_gold',
            'password' => Hash::make('password'),
            'email' => 'user39@example.com',
            'remember_token' => null,
            'no_wa' => '6281000000370',
            'balance' => 0,
            'role' => 'Member',
            'affiliate_status' => 'inactive',
            'idgame' => null,
            'servergame' => null,
            'idgame2' => null,
            'otp' => null,
            'google2fa_secret' => null,
            'created_at' => '2026-02-22 08:36:02',
            'updated_at' => '2026-02-22 08:36:02',
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null
        ],
        ]);
    }

    private function foreignKeyChecksEnabled(): bool
    {
        if (DB::getDriverName() !== 'mysql') {
            return true;
        }

        $row = DB::selectOne('SELECT @@FOREIGN_KEY_CHECKS AS checks_enabled');

        return (int) ($row->checks_enabled ?? 1) === 1;
    }
}