@php
    $onboardingTargets = [
        'dashboard' => '[data-onboarding-target="dashboard-stats"]',
        'revenue' => '[data-onboarding-target="dashboard-revenue"]',
        'activities' => '[data-onboarding-target="dashboard-activities"]',
        'ratings' => 'a[href="' . route('filament.admin.resources.ratings.index') . '"]',
        'products' => 'a[href="' . route('filament.admin.resources.produks.index') . '"]',
        'kategoris' => 'a[href="' . route('filament.admin.resources.kategoris.index') . '"]',
        'categoryTypes' => 'a[href="' . route('filament.admin.resources.category-types.index') . '"]',
        'pakets' => 'a[href="' . route('filament.admin.resources.pakets.index') . '"]',
        'artikels' => 'a[href="' . route('filament.admin.resources.artikels.index') . '"]',
        'methods' => 'a[href="' . route('filament.admin.resources.methods.index') . '"]',
        'pembelians' => 'a[href="' . route('filament.admin.resources.pembelians.index') . '"]',
        'users' => 'a[href="' . route('filament.admin.resources.users.index') . '"]',
        'deposits' => 'a[href="' . route('filament.admin.resources.deposits.index') . '"]',
        'providers' => 'a[href="' . route('filament.admin.resources.providers.index') . '"]',
        'beritas' => 'a[href="' . route('filament.admin.resources.beritas.index') . '"]',
        'settings' => 'a[href="' . route('filament.admin.pages.settings') . '"]',
        'vouchers' => 'a[href="' . route('filament.admin.resources.vouchers.index') . '"]',
        'mediaAssets' => 'a[href="' . route('filament.admin.resources.media-assets.index') . '"]',
        'emailTemplates' => 'a[href="' . route('filament.admin.resources.email-templates.index') . '"]',
        'whatsappTemplates' => 'a[href="' . route('filament.admin.resources.whatsapp-templates.index') . '"]',
        'whitelistedIps' => 'a[href="' . route('filament.admin.resources.whitelisted-i-ps.whitelisted-i-p-s.index') . '"]',
        'affiliateRequests' => 'a[href="' . route('filament.admin.resources.affiliate-requests.index') . '"]',
        'affiliateHistories' => 'a[href="' . route('filament.admin.resources.affiliate-histories.index') . '"]',
        'withdrawals' => 'a[href="' . route('filament.admin.resources.withdrawals.index') . '"]',
    ];

    $onboardingSteps = [
        [
            'targetKey' => 'dashboard',
            'title' => 'Ringkasan Dashboard',
            'description' => 'Di sini admin bisa melihat gambaran cepat performa toko, user, dan aktivitas terbaru.',
            'placement' => 'side',
        ],
        [
            'targetKey' => 'revenue',
            'title' => 'Chart Revenue',
            'description' => 'Bagian ini membantu admin membaca tren omzet dan performa penjualan dari waktu ke waktu.',
            'placement' => 'side',
        ],
        [
            'targetKey' => 'activities',
            'title' => 'Aktivitas Terbaru',
            'description' => 'Widget ini menampilkan leaderboard dan aktivitas penting agar admin cepat melihat dinamika transaksi.',
            'placement' => 'left',
        ],
        [
            'targetKey' => 'ratings',
            'title' => 'Ulasan Pembeli',
            'description' => 'Menu ini dipakai untuk memantau review pelanggan yang tampil di storefront dan menjaga kepercayaan toko.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'kategoris',
            'title' => 'Kategori Game',
            'description' => 'Atur kategori utama seperti Mobile Legends, Free Fire, pulsa, atau layanan digital lain dari sini.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'categoryTypes',
            'title' => 'Tipe Kategori',
            'description' => 'Tipe kategori membantu mengelompokkan produk berdasarkan pola input, tampilan, dan alur order yang dipakai.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'products',
            'title' => 'Menu Products',
            'description' => 'Gunakan menu Products untuk kelola kategori, produk, paket, metode, dan konten terkait katalog.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'pakets',
            'title' => 'Paket Layanan',
            'description' => 'Paket layanan dipakai untuk mengelola opsi nominal atau bundle khusus agar katalog lebih fleksibel.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'artikels',
            'title' => 'Artikel & Berita',
            'description' => 'Bagian ini dipakai untuk membuat konten SEO, edukasi, dan artikel promosi yang mendukung traffic organik.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'methods',
            'title' => 'Payment Methods',
            'description' => 'Di sini admin mengatur metode pembayaran yang tampil di checkout, termasuk status aktif dan urutannya.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'pembelians',
            'title' => 'Menu Pembelians',
            'description' => 'Di sini admin memantau transaksi, status order, invoice, dan proses penyelesaian pesanan.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'users',
            'title' => 'Users',
            'description' => 'Menu users dipakai untuk melihat akun pelanggan, admin, dan data profil yang berkaitan dengan operasional.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'deposits',
            'title' => 'Deposits',
            'description' => 'Bagian ini membantu admin memantau top up saldo member, approval deposit, dan histori pergerakan saldo.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'providers',
            'title' => 'Menu Providers',
            'description' => 'Bagian ini dipakai untuk cek saldo provider, sinkron data, dan memastikan jalur order tetap sehat.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'beritas',
            'title' => 'Banners & Popups',
            'description' => 'Gunakan menu ini untuk mengatur banner homepage, popup promo, dan materi promosi yang tampil ke pengunjung.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'settings',
            'title' => 'Menu Settings',
            'description' => 'Semua pengaturan branding, payment, tracking, notifikasi, dan SEO dikelola dari halaman Settings.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'vouchers',
            'title' => 'Vouchers',
            'description' => 'Voucher dipakai untuk promo diskon, campaign affiliate, atau potongan harga khusus di halaman order.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'mediaAssets',
            'title' => 'File Manager',
            'description' => 'File Manager memudahkan admin mengelola aset media seperti banner, logo, thumbnail, dan file pendukung lain.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'emailTemplates',
            'title' => 'Email Template',
            'description' => 'Di sini admin bisa mengatur template email agar notifikasi order dan pesan sistem tetap konsisten.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'whatsappTemplates',
            'title' => 'Whatsapp Template',
            'description' => 'Template WhatsApp membantu standarisasi pesan notifikasi dan follow-up ke pelanggan.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'whitelistedIps',
            'title' => 'Whitelisted IPs',
            'description' => 'Menu ini dipakai untuk membatasi IP tepercaya agar akses area tertentu dan callback lebih aman.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'affiliateRequests',
            'title' => 'Permintaan Affiliate',
            'description' => 'Bagian ini dipakai untuk meninjau pendaftaran affiliate baru sebelum disetujui oleh admin.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'affiliateHistories',
            'title' => 'Laporan Affiliate',
            'description' => 'Admin dapat memantau performa referral, komisi, dan histori affiliate dari halaman ini.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'withdrawals',
            'title' => 'Withdrawals',
            'description' => 'Menu withdrawals dipakai untuk memproses pencairan dana dan mengecek status penarikan affiliate atau user.',
            'placement' => 'right',
        ],
    ];
@endphp

@include('filament.admin.onboarding.partials.shell', [
    'guideBadge' => 'Panduan Admin Panel',
    'guideTitle' => 'Kenali area penting dashboard admin',
    'guideDescription' => 'Panduan singkat ini akan membantu admin memahami area utama panel, mulai dari ringkasan dashboard, produk, transaksi, provider, sampai pengaturan website.',
    'guideHighlights' => [
        'Dashboard: ringkasan performa toko',
        'Products: kelola kategori, produk, metode, dan konten',
        'Pembelians: monitor transaksi dan status order',
        'Providers: cek saldo dan sinkron provider',
        'Settings: branding, payment, tracking, dan SEO',
    ],
    'onboardingScope' => 'filament.admin.pages.dashboard',
    'onboardingTargets' => $onboardingTargets,
    'onboardingSteps' => $onboardingSteps,
])
