@php
    $onboardingTargets = [
        'dashboard' => '[data-onboarding-target="dashboard-stats"]',
        'revenue' => '[data-onboarding-target="dashboard-revenue"]',
        'activities' => '[data-onboarding-target="dashboard-activities"]',
        'ratings' => 'a[href="' . route('filament.admin.resources.ratings.index') . '"]',
        'products' => 'a[href="' . route('filament.admin.resources.produks.index') . '"]',
        'kategoris' => 'a[href="' . route('filament.admin.resources.kategoris.index') . '"]',
        'categoryTypes' => 'a[href="' . route('filament.admin.resources.category-types.index') . '"]',
        'pakets' => 'a[href="' . route('filament.admin.resources.pakets.index') . '"]',
        'artikels' => 'a[href="' . route('filament.admin.resources.artikels.index') . '"]',
        'methods' => 'a[href="' . route('filament.admin.resources.methods.index') . '"]',
        'pembelians' => 'a[href="' . route('filament.admin.resources.pembelians.index') . '"]',
        'users' => 'a[href="' . route('filament.admin.resources.users.index') . '"]',
        'deposits' => 'a[href="' . route('filament.admin.resources.deposits.index') . '"]',
        'providers' => 'a[href="' . route('filament.admin.resources.providers.index') . '"]',
        'beritas' => 'a[href="' . route('filament.admin.resources.beritas.index') . '"]',
        'settings' => 'a[href="' . route('filament.admin.pages.settings') . '"]',
        'vouchers' => 'a[href="' . route('filament.admin.resources.vouchers.index') . '"]',
        'mediaAssets' => 'a[href="' . route('filament.admin.resources.media-assets.index') . '"]',
        'emailTemplates' => 'a[href="' . route('filament.admin.resources.email-templates.index') . '"]',
        'whatsappTemplates' => 'a[href="' . route('filament.admin.resources.whatsapp-templates.index') . '"]',
        'pushTemplates' => 'a[href="' . \App\Filament\Admin\Resources\PushNotificationTemplateResource::getUrl() . '"]',
        'pushBroadcast' => 'a[href="' . \App\Filament\Admin\Pages\PushNotificationBroadcast::getUrl() . '"]',
        'inboundWhitelist' => 'a[href="' . \App\Filament\Admin\Resources\InboundSourcePolicies\InboundSourcePolicyResource::getUrl() . '"]',
        'affiliateRequests' => 'a[href="' . route('filament.admin.resources.affiliate-requests.index') . '"]',
        'affiliateHistories' => 'a[href="' . route('filament.admin.resources.affiliate-histories.index') . '"]',
        'withdrawals' => \Illuminate\Support\Facades\Route::has('filament.admin.resources.withdrawals.index')
            ? 'a[href="' . route('filament.admin.resources.withdrawals.index') . '"]'
            : null,
    ];

    $onboardingSteps = [
        [
            'targetKey' => 'dashboard',
            'title' => 'Ringkasan Dashboard',
            'description' => 'Lihat performa toko, user, dan aktivitas terbaru dalam satu tampilan cepat.',
            'placement' => 'side',
        ],
        [
            'targetKey' => 'revenue',
            'title' => 'Chart Revenue',
            'description' => 'Pantau tren omzet dan performa penjualan dari waktu ke waktu.',
            'placement' => 'side',
        ],
        [
            'targetKey' => 'activities',
            'title' => 'Aktivitas Terbaru',
            'description' => 'Cek aktivitas penting dan leaderboard tanpa membuka banyak halaman.',
            'placement' => 'left',
        ],
        [
            'targetKey' => 'ratings',
            'title' => 'Ulasan Pembeli',
            'description' => 'Pantau review pelanggan yang tampil di storefront.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'kategoris',
            'title' => 'Kategori Game',
            'description' => 'Kelola kategori utama seperti game, pulsa, atau layanan digital lain.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'categoryTypes',
            'title' => 'Tipe Kategori',
            'description' => 'Atur pola input dan tampilan order sesuai jenis produk.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'products',
            'title' => 'Menu Products',
            'description' => 'Kelola katalog: kategori, produk, paket, metode, dan konten pendukung.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'pakets',
            'title' => 'Paket Layanan',
            'description' => 'Kelola nominal, variasi, atau bundle produk yang dijual.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'artikels',
            'title' => 'Artikel & Berita',
            'description' => 'Buat konten SEO, edukasi, dan promo untuk pengunjung.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'methods',
            'title' => 'Payment Methods',
            'description' => 'Atur metode pembayaran yang tampil di checkout.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'pembelians',
            'title' => 'Menu Pembelians',
            'description' => 'Pantau transaksi, invoice, dan status penyelesaian pesanan.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'users',
            'title' => 'Users',
            'description' => 'Lihat akun pelanggan, admin, dan data profil operasional.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'deposits',
            'title' => 'Deposits',
            'description' => 'Pantau top up saldo member dan histori deposit.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'providers',
            'title' => 'Menu Providers',
            'description' => 'Cek saldo provider dan kesehatan jalur order.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'beritas',
            'title' => 'Banners & Popups',
            'description' => 'Atur banner, popup promo, dan materi promosi storefront.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'settings',
            'title' => 'Menu Settings',
            'description' => 'Kelola branding, payment, notifikasi, tracking, dan SEO.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'vouchers',
            'title' => 'Vouchers',
            'description' => 'Buat promo diskon atau potongan harga khusus.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'mediaAssets',
            'title' => 'File Manager',
            'description' => 'Kelola aset media seperti banner, logo, dan thumbnail.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'emailTemplates',
            'title' => 'Template Email',
            'description' => 'Atur isi email otomatis untuk status transaksi pelanggan.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'whatsappTemplates',
            'title' => 'Template WhatsApp',
            'description' => 'Atur pesan WhatsApp otomatis berdasarkan status transaksi.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'pushTemplates',
            'title' => 'Template Push PWA',
            'description' => 'Atur notifikasi PWA otomatis untuk event order penting.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'pushBroadcast',
            'title' => 'Push Broadcast',
            'description' => 'Kirim pengumuman singkat ke user yang mengaktifkan PWA.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'inboundWhitelist',
            'title' => 'Inbound Whitelist',
            'description' => 'Menu ini dipakai untuk mengelola IP atau CIDR tepercaya bagi callback supplier dan payment gateway.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'affiliateRequests',
            'title' => 'Permintaan Affiliate',
            'description' => 'Bagian ini dipakai untuk meninjau pendaftaran affiliate baru sebelum disetujui oleh admin.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'affiliateHistories',
            'title' => 'Laporan Affiliate',
            'description' => 'Admin dapat memantau performa referral, komisi, dan histori affiliate dari halaman ini.',
            'placement' => 'right',
        ],
        [
            'targetKey' => 'withdrawals',
            'title' => 'Withdrawals',
            'description' => 'Menu withdrawals dipakai untuk memproses pencairan dana dan mengecek status penarikan affiliate atau user.',
            'placement' => 'right',
        ],
    ];
@endphp

@include('filament.admin.onboarding.partials.shell', [
    'guideBadge' => 'Panduan Admin Panel',
    'guideTitle' => 'Kenali area penting dashboard admin',
    'guideDescription' => 'Panduan singkat ini akan membantu admin memahami area utama panel, mulai dari ringkasan dashboard, produk, transaksi, provider, sampai pengaturan website.',
    'guideHighlights' => [
        'Dashboard: ringkasan performa toko',
        'Products: kelola kategori, produk, metode, dan konten',
        'Pembelians: monitor transaksi dan status order',
        'Providers: cek saldo dan sinkron provider',
        'Settings: branding, payment, tracking, dan SEO',
    ],
    'onboardingScope' => 'filament.admin.pages.dashboard',
    'onboardingTargets' => $onboardingTargets,
    'onboardingSteps' => $onboardingSteps,
])
