@php
    $currentRouteName = request()->route()?->getName();

    $pageGuides = [
        'filament.admin.resources.pembelians.index' => [
            'guideBadge' => 'Panduan Order Management',
            'guideTitle' => 'Kelola transaksi dari satu halaman',
            'guideDescription' => 'Halaman ini dipakai admin untuk membaca tabel transaksi dengan lebih rapi: pahami arti tiap kolom yang tampil, lalu gunakan action order sesuai kebutuhan operasional.',
            'guideHighlights' => [
                'Kolom yang sedang tampil akan dijelaskan satu per satu.',
                'Kolom yang sedang disembunyikan belum dibahas di panduan ini.',
                'Bagian action order juga dijelaskan supaya admin tahu kapan fitur tertentu dipakai.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.resources.pembelians.index') . '"]',
                'header' => '.fi-header',
                'invoice' => '.fi-ta thead th:nth-child(2)',
                'nickname' => '.fi-ta thead th:nth-child(3)',
                'product' => '.fi-ta thead th:nth-child(4)',
                'providerStatus' => '.fi-ta thead th:nth-child(5)',
                'dispatch' => '.fi-ta thead th:nth-child(6)',
                'paymentStatus' => '.fi-ta thead th:nth-child(7)',
                'phone' => '.fi-ta thead th:nth-child(8)',
                'serial' => '.fi-ta thead th:nth-child(9)',
                'points' => '.fi-ta thead th:nth-child(10)',
                'amount' => '.fi-ta thead th:nth-child(11)',
                'method' => '.fi-ta thead th:nth-child(12)',
                'orderDate' => '.fi-ta thead th:nth-child(13)',
                'actionsButton' => '.fi-ta tbody tr:first-child td:last-child button',
                'actionViewDetail' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(1)',
                'actionEditStatus' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(2)',
                'actionProcess' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(3)',
                'actionRetry' => '.fi-dropdown-panel .fi-dropdown-list-item:last-of-type',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Order Management',
                    'description' => 'Masuk ke halaman ini saat kamu ingin fokus ke order, invoice, dan status transaksi pelanggan.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'header',
                    'title' => 'Ringkasan Halaman Order',
                    'description' => 'Bagian header membantu admin tahu bahwa halaman ini adalah pusat pantau order dan tindak lanjut operasional.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'invoice',
                    'title' => 'Kolom Invoice',
                    'description' => 'Kolom ini dipakai untuk mengenali order utama. Invoice biasanya jadi acuan saat cari transaksi, cek callback, atau bantu customer support.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'nickname',
                    'title' => 'Kolom Nickname',
                    'description' => 'Di sini admin bisa melihat nama akun atau nickname yang dipakai customer pada order tersebut.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'product',
                    'title' => 'Kolom Product',
                    'description' => 'Kolom ini menunjukkan produk yang dibeli customer. Deskripsi kecil di bawahnya membantu melihat sumber traffic atau konteks tambahan order.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'providerStatus',
                    'title' => 'Kolom Status Provider',
                    'description' => 'Status ini menunjukkan kondisi order dari sisi provider, misalnya masih pending, sedang diproses, sukses, atau gagal.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'dispatch',
                    'title' => 'Kolom Dispatch',
                    'description' => 'Dispatch membantu admin melihat apakah order sedang antre, idle, atau sudah didorong ke jalur provider.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'paymentStatus',
                    'title' => 'Kolom Status Pembelian',
                    'description' => 'Bagian ini menunjukkan status dari sisi pembayaran customer, misalnya masih pending atau sudah lunas.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'phone',
                    'title' => 'Kolom Nomor Telp',
                    'description' => 'Nomor telepon customer ditampilkan di sini agar admin bisa verifikasi data order atau membantu follow-up bila diperlukan.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'serial',
                    'title' => 'Kolom Keterangan / SN',
                    'description' => 'Kolom ini berisi serial number, catatan hasil pengiriman, atau placeholder jika order belum menghasilkan SN.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'points',
                    'title' => 'Kolom Poin',
                    'description' => 'Jika customer memakai poin, nilai pemakaiannya akan terlihat di sini. Kalau tidak ada, kolom ini biasanya berisi tanda strip.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'amount',
                    'title' => 'Kolom Amount',
                    'description' => 'Amount menunjukkan nominal akhir transaksi yang dibayar customer setelah potongan, poin, atau penyesuaian lain.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'method',
                    'title' => 'Kolom Metode',
                    'description' => 'Di sini admin bisa melihat metode pembayaran yang dipilih, termasuk gateway atau metode manual yang dipakai saat checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'orderDate',
                    'title' => 'Kolom Order Date',
                    'description' => 'Kolom tanggal membantu admin membaca urutan waktu order dibuat dan memudahkan pelacakan transaksi terbaru atau lama.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'actionsButton',
                    'title' => 'Menu Action Order',
                    'description' => 'Tombol action ini membuka daftar aksi untuk order terkait. Dari sinilah admin masuk ke detail, ubah status, atau menjalankan tindakan operasional lain.',
                    'placement' => 'top',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel',
                    ],
                ],
                [
                    'targetKey' => 'actionViewDetail',
                    'title' => 'Action: View Detail',
                    'description' => 'Gunakan View Detail saat admin ingin melihat isi order lebih lengkap, termasuk data customer, log, dan histori order.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(1)',
                    ],
                ],
                [
                    'targetKey' => 'actionEditStatus',
                    'title' => 'Action: Ubah Status',
                    'description' => 'Fitur ini dipakai saat admin perlu mengoreksi atau menyesuaikan status transaksi secara manual setelah verifikasi internal.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(2)',
                    ],
                ],
                [
                    'targetKey' => 'actionProcess',
                    'title' => 'Action: Process / Cancel / Refund',
                    'description' => 'Aksi ini dipakai sesuai kondisi order: memproses order, membatalkan order, atau melakukan refund bila memang diperlukan.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(3)',
                    ],
                ],
                [
                    'targetKey' => 'actionRetry',
                    'title' => 'Action: Retry / Resend Notif',
                    'description' => 'Retry membantu mengirim ulang order ke provider jika perlu dicek ulang. Resend Notif dipakai untuk kirim ulang notifikasi ke customer.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:last-of-type',
                    ],
                ],
            ],
        ],
        'filament.admin.resources.produks.create' => [
            'guideBadge' => 'Panduan Buat Produk',
            'guideTitle' => 'Susun produk baru dengan alur yang jelas',
            'guideDescription' => 'Halaman ini dipakai untuk membuat produk baru lengkap dengan kategori, provider, harga, media, dan relasi paket layanan.',
            'guideHighlights' => [
                'Pilih kategori dan isi nama produk agar katalog tetap rapi.',
                'Hubungkan produk ke provider yang benar.',
                'Cek harga, media, dan simpan setelah semua field inti siap.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.resources.produks.index') . '"]',
                'header' => '.fi-header',
                'category' => '[wire\\:model*="data.kategori_id"]',
                'provider' => '[wire\\:model*="data.provider"]',
                'pricing' => '[wire\\:model*="data.harga"]',
                'save' => 'main form button[type="submit"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Produk',
                    'description' => 'Menu ini membawa admin ke seluruh pengelolaan katalog, termasuk daftar produk dan pembuatan produk baru.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'header',
                    'title' => 'Halaman Create Produk',
                    'description' => 'Di sini admin menyiapkan semua data inti produk sebelum produk tampil di storefront dan bisa dijual.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'category',
                    'title' => 'Kategori Produk',
                    'description' => 'Mulai dari memilih kategori yang tepat supaya produk masuk ke halaman game atau layanan yang sesuai.',
                    'placement' => 'side',
                ],
                [
                    'targetKey' => 'provider',
                    'title' => 'Sumber Provider',
                    'description' => 'Pilih provider yang benar agar provider ID, sinkron harga, dan jalur pemrosesan order tetap konsisten.',
                    'placement' => 'side',
                ],
                [
                    'targetKey' => 'pricing',
                    'title' => 'Harga Dasar',
                    'description' => 'Bagian harga dipakai untuk menetapkan modal dan harga jual agar margin produk tetap terkontrol.',
                    'placement' => 'side',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Produk',
                    'description' => 'Setelah kategori, provider, harga, dan media sudah benar, simpan produk untuk menambahkannya ke katalog.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.resources.methods.index' => [
            'guideBadge' => 'Panduan Payment Methods',
            'guideTitle' => 'Kelola metode pembayaran yang tampil di checkout',
            'guideDescription' => 'Halaman ini dipakai untuk membaca dan mengelola metode pembayaran dengan lebih rapi: pahami arti tiap kolom yang tampil, lalu gunakan action yang sesuai saat ingin menambah atau mengubah metode.',
            'guideHighlights' => [
                'Kolom yang sedang tampil akan dijelaskan satu per satu.',
                'Fokus panduan ini hanya pada kolom yang benar-benar terlihat di tabel.',
                'Area action juga dijelaskan supaya admin tahu kapan harus tambah atau edit metode.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.resources.methods.index') . '"]',
                'header' => '.fi-header',
                'actions' => '.fi-header-actions',
                'logo' => '.fi-ta thead th:nth-child(1)',
                'name' => '.fi-ta thead th:nth-child(2)',
                'code' => '.fi-ta thead th:nth-child(3)',
                'type' => '.fi-ta thead th:nth-child(4)',
                'gateway' => '.fi-ta thead th:nth-child(5)',
                'feePercent' => '.fi-ta thead th:nth-child(6)',
                'fixedFee' => '.fi-ta thead th:nth-child(7)',
                'minimum' => '.fi-ta thead th:nth-child(8)',
                'maximum' => '.fi-ta thead th:nth-child(9)',
                'status' => '.fi-ta thead th:nth-child(10)',
                'createdAt' => '.fi-ta thead th:nth-child(11)',
                'rowAction' => '.fi-ta tbody tr:first-child td:last-child a, .fi-ta tbody tr:first-child td:last-child button',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Payment Methods',
                    'description' => 'Gunakan menu ini untuk masuk ke daftar seluruh metode pembayaran yang tersedia di toko.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'header',
                    'title' => 'Ringkasan Halaman Payment',
                    'description' => 'Header halaman membantu admin memastikan bahwa perubahan yang dilakukan akan berdampak langsung ke checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'actions',
                    'title' => 'Aksi Tambah Metode',
                    'description' => 'Dari area ini admin bisa menambah metode baru atau memakai action yang tersedia untuk kebutuhan manajemen payment.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'logo',
                    'title' => 'Kolom Logo',
                    'description' => 'Kolom ini membantu admin mengenali metode pembayaran secara visual melalui logo atau ikon yang tampil di checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'name',
                    'title' => 'Kolom Nama Metode',
                    'description' => 'Nama metode dipakai sebagai label utama yang dibaca customer saat memilih pembayaran.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'code',
                    'title' => 'Kolom Kode',
                    'description' => 'Kode metode dipakai di sistem untuk pemetaan gateway, callback, dan identitas metode secara teknis.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'type',
                    'title' => 'Kolom Tipe',
                    'description' => 'Tipe membantu admin membedakan apakah metode ini bank transfer, e-wallet, QRIS, virtual account, atau convenience store.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'gateway',
                    'title' => 'Kolom Gateway',
                    'description' => 'Gateway menunjukkan provider pembayaran yang menangani metode tersebut, misalnya manual, Tripay, Tokopay, atau Paydisini.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'feePercent',
                    'title' => 'Kolom Fee Persen',
                    'description' => 'Bagian ini menunjukkan biaya persentase yang dibebankan ke metode pembayaran tersebut.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'fixedFee',
                    'title' => 'Kolom Fix Fee',
                    'description' => 'Fix fee dipakai untuk melihat biaya tetap per transaksi yang akan dikenakan selain biaya persentase.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'minimum',
                    'title' => 'Kolom Minimum',
                    'description' => 'Nilai minimum membantu admin memastikan metode ini hanya tersedia jika nominal transaksi memenuhi batas minimal.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'maximum',
                    'title' => 'Kolom Maximum',
                    'description' => 'Batas maksimum dipakai agar metode tidak muncul untuk transaksi yang melewati nominal tertentu.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'status',
                    'title' => 'Kolom Status',
                    'description' => 'Status menunjukkan apakah metode aktif dan bisa dipakai customer, atau sedang dinonaktifkan dari checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'createdAt',
                    'title' => 'Kolom Dibuat',
                    'description' => 'Kolom tanggal pembuatan memudahkan admin melihat kapan metode ini pertama kali ditambahkan ke sistem.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'rowAction',
                    'title' => 'Action: Edit Metode',
                    'description' => 'Gunakan action pada tiap baris untuk membuka editor metode, lalu ubah fee, status, logo, atau aturan nominal sesuai kebutuhan.',
                    'placement' => 'left',
                ],
            ],
        ],
        'filament.admin.pages.settings' => [
            'guideBadge' => 'Panduan Settings',
            'guideTitle' => 'Atur branding, tracking, SEO, dan operasional website',
            'guideDescription' => 'Halaman Settings adalah pusat pengaturan utama toko. Panduan ini akan menjelaskan fungsi tiap section penting satu per satu supaya admin tahu harus mengubah bagian mana saat ada kebutuhan tertentu.',
            'guideHighlights' => [
                'Setiap section dijelaskan berdasarkan fungsi operasionalnya.',
                'Admin bisa langsung tahu di mana harus mengubah branding, tracking, provider, payment gateway, atau reward system.',
                'Akhiri dengan tombol simpan agar semua perubahan aktif.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.pages.settings') . '"]',
                'websiteInfo' => '[data-onboarding-target="settings-website-information"]',
                'analytics' => '[data-onboarding-target="settings-analytics-tracking"]',
                'homePopup' => '[data-onboarding-target="settings-homepage-popup"]',
                'liveSales' => '[data-onboarding-target="settings-live-sales"]',
                'seo' => '[data-onboarding-target="settings-seo"]',
                'captcha' => '[data-onboarding-target="settings-admin-captcha"]',
                'branding' => '[data-onboarding-target="settings-branding"]',
                'seasonal' => '[data-onboarding-target="settings-seasonal-theme"]',
                'socialMedia' => '[data-onboarding-target="settings-social-media"]',
                'topupindo' => '[data-onboarding-target="settings-topupindo"]',
                'bangjeff' => '[data-onboarding-target="settings-bangjeff"]',
                'aoshi' => '[data-onboarding-target="settings-aoshi"]',
                'mobileGameStore' => '[data-onboarding-target="settings-mobile-game-store"]',
                'vipReseller' => '[data-onboarding-target="settings-vip-reseller"]',
                'depositConfiguration' => '[data-onboarding-target="settings-deposit-configuration"]',
                'paydisini' => '[data-onboarding-target="settings-paydisini"]',
                'tripay' => '[data-onboarding-target="settings-tripay"]',
                'tokopay' => '[data-onboarding-target="settings-tokopay"]',
                'duitku' => '[data-onboarding-target="settings-duitku"]',
                'digiflazz' => '[data-onboarding-target="settings-digiflazz"]',
                'apiGames' => '[data-onboarding-target="settings-api-games"]',
                'whatsapp' => '[data-onboarding-target="settings-whatsapp-configuration"]',
                'mail' => '[data-onboarding-target="settings-mail-configuration"]',
                'invoiceDelivery' => '[data-onboarding-target="settings-invoice-delivery"]',
                'ewalletAccounts' => '[data-onboarding-target="settings-ewallet-accounts"]',
                'bankAccount' => '[data-onboarding-target="settings-bank-account"]',
                'tierMarkup' => '[data-onboarding-target="settings-tier-markup"]',
                'tierSystem' => '[data-onboarding-target="settings-tier-system"]',
                'pointSystem' => '[data-onboarding-target="settings-point-system"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Settings',
                    'description' => 'Menu ini membuka pusat konfigurasi toko, mulai dari branding, tracking, popup homepage, hingga SEO.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'websiteInfo',
                    'title' => 'Section Website Information',
                    'description' => 'Bagian ini dipakai untuk mengatur judul website, prefix order, deskripsi, dan keyword SEO dasar.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'analytics',
                    'title' => 'Section Analytics & Tracking',
                    'description' => 'Di sini admin mengatur GA4, Facebook Pixel, GTM standar, atau custom GTM snippet untuk kebutuhan tracking dan conversion.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'homePopup',
                    'title' => 'Section Homepage Popup',
                    'description' => 'Section ini dipakai untuk menyalakan atau mematikan popup homepage tanpa perlu ubah kode.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'liveSales',
                    'title' => 'Section Live Sales Toast',
                    'description' => 'Gunakan bagian ini untuk mengontrol apakah toast transaksi terbaru tampil di homepage atau tidak.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'seo',
                    'title' => 'Section SEO Crawling',
                    'description' => 'Area SEO dipakai untuk mengatur robots.txt, sitemap.xml, custom sitemap upload, dan preview aturan crawling.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'captcha',
                    'title' => 'Section Admin Login CAPTCHA',
                    'description' => 'Bagian ini membantu admin mengaktifkan CAPTCHA login panel admin dan mengatur bypass darurat bila diperlukan.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'branding',
                    'title' => 'Section Logo & Colors',
                    'description' => 'Section branding dipakai untuk mengatur logo header, footer, favicon, dan warna utama website.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'seasonal',
                    'title' => 'Section Seasonal Theme',
                    'description' => 'Jika ingin tema musiman seperti Ramadhan atau Halloween, semua pengaturannya ada di bagian ini.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'socialMedia',
                    'title' => 'Section Social Media Links',
                    'description' => 'Gunakan section ini untuk mengisi link WhatsApp, Instagram, TikTok, YouTube, dan Facebook yang tampil ke pengunjung.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'topupindo',
                    'title' => 'Section TopUpIndo',
                    'description' => 'Bagian ini menyimpan API key TopUpIndo untuk kebutuhan provider dan sinkronisasi yang memakai layanan tersebut.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'bangjeff',
                    'title' => 'Section BangJeff',
                    'description' => 'Di sini admin mengisi API key BangJeff agar order dan sinkronisasi provider BangJeff bisa berjalan.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'aoshi',
                    'title' => 'Section Aoshi',
                    'description' => 'Section ini dipakai untuk menyimpan secret atau API key dari provider Aoshi.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'mobileGameStore',
                    'title' => 'Section Mobile Game Store',
                    'description' => 'Isi API key Mobile Game Store di sini jika client memakai provider tersebut untuk jalur order.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'vipReseller',
                    'title' => 'Section VIP Reseller',
                    'description' => 'Bagian ini menyimpan API ID, API Key, dan sign VIP Reseller yang dibutuhkan untuk request provider.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'depositConfiguration',
                    'title' => 'Section Deposit Configuration',
                    'description' => 'Section ini dipakai untuk memilih gateway deposit QRIS aktif yang dipakai sistem.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'paydisini',
                    'title' => 'Section PayDisini',
                    'description' => 'Isi API key PayDisini di sini jika metode pembayaran memakai gateway PayDisini.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'tripay',
                    'title' => 'Section Tripay',
                    'description' => 'Bagian ini dipakai untuk menyimpan API key, merchant code, dan private key TriPay.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'tokopay',
                    'title' => 'Section TokoPay',
                    'description' => 'Di sini admin mengisi merchant ID dan secret key Tokopay untuk invoice dan callback pembayaran.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'duitku',
                    'title' => 'Section Duitku',
                    'description' => 'Section ini mencakup merchant code, merchant key, mode sandbox/production, dan pengaturan callback Duitku.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'digiflazz',
                    'title' => 'Section Digiflazz',
                    'description' => 'Bagian Digiflazz dipakai untuk menyimpan username buyer dan API key dari dashboard Digiflazz.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'apiGames',
                    'title' => 'Section API Games',
                    'description' => 'Di sini admin mengisi Merchant ID dan Secret Key API Games untuk kebutuhan provider serta cek balance.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'whatsapp',
                    'title' => 'Section WhatsApp Configuration',
                    'description' => 'Section ini mengatur provider WhatsApp, nomor admin, token/API key, dan mode integrasi pengiriman pesan.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'mail',
                    'title' => 'Section Mail Configuration',
                    'description' => 'Gunakan bagian ini untuk mengatur SMTP, email pengirim, dan test email tanpa perlu edit file environment.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'invoiceDelivery',
                    'title' => 'Section Invoice Delivery Channels',
                    'description' => 'Bagian ini mengatur apakah invoice dikirim lewat WhatsApp, email, atau keduanya.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'ewalletAccounts',
                    'title' => 'Section E-Wallet Accounts',
                    'description' => 'Jika client memakai metode manual, nomor akun OVO, GoPay, DANA, dan ShopeePay diisi dari sini.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'bankAccount',
                    'title' => 'Section Bank Account',
                    'description' => 'Section ini dipakai untuk menyimpan rekening bank manual yang tampil di metode pembayaran tertentu.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'tierMarkup',
                    'title' => 'Section Tier Markup Settings',
                    'description' => 'Bagian ini membantu admin menentukan markup default untuk member, gold, dan platinum.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'tierSystem',
                    'title' => 'Section Tier System Configuration',
                    'description' => 'Di sini admin mengatur ambang transaksi sukses untuk kenaikan tier user otomatis.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'pointSystem',
                    'title' => 'Section Point System Configuration',
                    'description' => 'Section poin dipakai untuk menentukan rasio poin, nilai satu poin, dan batas maksimal pemakaian poin.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Setelah semua pengaturan selesai dicek, gunakan tombol ini agar perubahan langsung tersimpan dan dipakai website.',
                    'placement' => 'top',
                ],
            ],
        ],
    ];

    $guide = $pageGuides[$currentRouteName] ?? null;
@endphp

@if ($guide)
    @include('filament.admin.onboarding.partials.shell', [
        'guideBadge' => $guide['guideBadge'],
        'guideTitle' => $guide['guideTitle'],
        'guideDescription' => $guide['guideDescription'],
        'guideHighlights' => $guide['guideHighlights'],
        'onboardingTargets' => $guide['targets'],
        'onboardingSteps' => $guide['steps'],
    ])
@endif
