@php
    $currentRouteName = request()->route()?->getName();

    $pageGuides = [
        'filament.admin.resources.pembelians.index' => [
            'guideBadge' => 'Panduan Order Management',
            'guideTitle' => 'Kelola transaksi dari satu halaman',
            'guideDescription' => 'Halaman ini dipakai admin untuk membaca tabel transaksi dengan lebih rapi: pahami arti tiap kolom yang tampil, lalu gunakan action order sesuai kebutuhan operasional.',
            'guideHighlights' => [
                'Kolom yang sedang tampil akan dijelaskan satu per satu.',
                'Kolom yang sedang disembunyikan belum dibahas di panduan ini.',
                'Bagian action order juga dijelaskan supaya admin tahu kapan fitur tertentu dipakai.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.resources.pembelians.index') . '"]',
                'header' => '.fi-header',
                'invoice' => '.fi-ta thead th:nth-child(2)',
                'nickname' => '.fi-ta thead th:nth-child(3)',
                'product' => '.fi-ta thead th:nth-child(4)',
                'providerStatus' => '.fi-ta thead th:nth-child(5)',
                'dispatch' => '.fi-ta thead th:nth-child(6)',
                'paymentStatus' => '.fi-ta thead th:nth-child(7)',
                'phone' => '.fi-ta thead th:nth-child(8)',
                'serial' => '.fi-ta thead th:nth-child(9)',
                'points' => '.fi-ta thead th:nth-child(10)',
                'amount' => '.fi-ta thead th:nth-child(11)',
                'method' => '.fi-ta thead th:nth-child(12)',
                'orderDate' => '.fi-ta thead th:nth-child(13)',
                'actionsButton' => '.fi-ta tbody tr:first-child td:last-child button',
                'actionViewDetail' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(1)',
                'actionEditStatus' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(2)',
                'actionProcess' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(3)',
                'actionRetry' => '.fi-dropdown-panel .fi-dropdown-list-item:last-of-type',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Order Management',
                    'description' => 'Masuk ke halaman ini saat kamu ingin fokus ke order, invoice, dan status transaksi pelanggan.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'header',
                    'title' => 'Ringkasan Halaman Order',
                    'description' => 'Bagian header membantu admin tahu bahwa halaman ini adalah pusat pantau order dan tindak lanjut operasional.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'invoice',
                    'title' => 'Kolom Invoice',
                    'description' => 'Kolom ini dipakai untuk mengenali order utama. Invoice biasanya jadi acuan saat cari transaksi, cek callback, atau bantu customer support.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'nickname',
                    'title' => 'Kolom Nickname',
                    'description' => 'Di sini admin bisa melihat nama akun atau nickname yang dipakai customer pada order tersebut.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'product',
                    'title' => 'Kolom Product',
                    'description' => 'Kolom ini menunjukkan produk yang dibeli customer. Deskripsi kecil di bawahnya membantu melihat sumber traffic atau konteks tambahan order.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'providerStatus',
                    'title' => 'Kolom Status Provider',
                    'description' => 'Status ini menunjukkan kondisi order dari sisi provider, misalnya masih pending, sedang diproses, sukses, atau gagal.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'dispatch',
                    'title' => 'Kolom Dispatch',
                    'description' => 'Dispatch membantu admin melihat apakah order sedang antre, idle, atau sudah didorong ke jalur provider.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'paymentStatus',
                    'title' => 'Kolom Status Pembelian',
                    'description' => 'Bagian ini menunjukkan status dari sisi pembayaran customer, misalnya masih pending atau sudah lunas.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'phone',
                    'title' => 'Kolom Nomor Telp',
                    'description' => 'Nomor telepon customer ditampilkan di sini agar admin bisa verifikasi data order atau membantu follow-up bila diperlukan.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'serial',
                    'title' => 'Kolom Keterangan / SN',
                    'description' => 'Kolom ini berisi serial number, catatan hasil pengiriman, atau placeholder jika order belum menghasilkan SN.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'points',
                    'title' => 'Kolom Poin',
                    'description' => 'Jika customer memakai poin, nilai pemakaiannya akan terlihat di sini. Kalau tidak ada, kolom ini biasanya berisi tanda strip.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'amount',
                    'title' => 'Kolom Amount',
                    'description' => 'Amount menunjukkan nominal akhir transaksi yang dibayar customer setelah potongan, poin, atau penyesuaian lain.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'method',
                    'title' => 'Kolom Metode',
                    'description' => 'Di sini admin bisa melihat metode pembayaran yang dipilih, termasuk gateway atau metode manual yang dipakai saat checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'orderDate',
                    'title' => 'Kolom Order Date',
                    'description' => 'Kolom tanggal membantu admin membaca urutan waktu order dibuat dan memudahkan pelacakan transaksi terbaru atau lama.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'actionsButton',
                    'title' => 'Menu Action Order',
                    'description' => 'Tombol action ini membuka daftar aksi untuk order terkait. Dari sinilah admin masuk ke detail, ubah status, atau menjalankan tindakan operasional lain.',
                    'placement' => 'top',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel',
                    ],
                ],
                [
                    'targetKey' => 'actionViewDetail',
                    'title' => 'Action: View Detail',
                    'description' => 'Gunakan View Detail saat admin ingin melihat isi order lebih lengkap, termasuk data customer, log, dan histori order.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(1)',
                    ],
                ],
                [
                    'targetKey' => 'actionEditStatus',
                    'title' => 'Action: Ubah Status',
                    'description' => 'Fitur ini dipakai saat admin perlu mengoreksi atau menyesuaikan status transaksi secara manual setelah verifikasi internal.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(2)',
                    ],
                ],
                [
                    'targetKey' => 'actionProcess',
                    'title' => 'Action: Process / Cancel / Refund',
                    'description' => 'Aksi ini dipakai sesuai kondisi order: memproses order, membatalkan order, atau melakukan refund bila memang diperlukan.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:nth-of-type(3)',
                    ],
                ],
                [
                    'targetKey' => 'actionRetry',
                    'title' => 'Action: Retry / Resend Notif',
                    'description' => 'Retry membantu mengirim ulang order ke provider jika perlu dicek ulang. Resend Notif dipakai untuk kirim ulang notifikasi ke customer.',
                    'placement' => 'left',
                    'interaction' => [
                        'group' => 'order-actions',
                        'openTargetKey' => 'actionsButton',
                        'keepOpen' => true,
                        'focusSelector' => '.fi-dropdown-panel .fi-dropdown-list-item:last-of-type',
                    ],
                ],
            ],
        ],
        'filament.admin.resources.produks.create' => [
            'guideBadge' => 'Panduan Buat Produk',
            'guideTitle' => 'Susun produk baru dengan alur yang jelas',
            'guideDescription' => 'Halaman ini dipakai untuk membuat produk baru lengkap dengan kategori, provider, harga, media, dan relasi paket layanan.',
            'guideHighlights' => [
                'Pilih kategori dan isi nama produk agar katalog tetap rapi.',
                'Hubungkan produk ke provider yang benar.',
                'Cek harga, media, dan simpan setelah semua field inti siap.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.resources.produks.index') . '"]',
                'header' => '.fi-header',
                'category' => '[wire\\:model*="data.kategori_id"]',
                'provider' => '[wire\\:model*="data.provider"]',
                'pricing' => '[wire\\:model*="data.harga"]',
                'save' => 'main form button[type="submit"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Produk',
                    'description' => 'Menu ini membawa admin ke seluruh pengelolaan katalog, termasuk daftar produk dan pembuatan produk baru.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'header',
                    'title' => 'Halaman Create Produk',
                    'description' => 'Di sini admin menyiapkan semua data inti produk sebelum produk tampil di storefront dan bisa dijual.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'category',
                    'title' => 'Kategori Produk',
                    'description' => 'Mulai dari memilih kategori yang tepat supaya produk masuk ke halaman game atau layanan yang sesuai.',
                    'placement' => 'side',
                ],
                [
                    'targetKey' => 'provider',
                    'title' => 'Sumber Provider',
                    'description' => 'Pilih provider yang benar agar provider ID, sinkron harga, dan jalur pemrosesan order tetap konsisten.',
                    'placement' => 'side',
                ],
                [
                    'targetKey' => 'pricing',
                    'title' => 'Harga Dasar',
                    'description' => 'Bagian harga dipakai untuk menetapkan modal dan harga jual agar margin produk tetap terkontrol.',
                    'placement' => 'side',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Produk',
                    'description' => 'Setelah kategori, provider, harga, dan media sudah benar, simpan produk untuk menambahkannya ke katalog.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.resources.methods.index' => [
            'guideBadge' => 'Panduan Payment Methods',
            'guideTitle' => 'Kelola metode pembayaran yang tampil di checkout',
            'guideDescription' => 'Halaman ini dipakai untuk membaca dan mengelola metode pembayaran dengan lebih rapi: pahami arti tiap kolom yang tampil, lalu gunakan action yang sesuai saat ingin menambah atau mengubah metode.',
            'guideHighlights' => [
                'Kolom yang sedang tampil akan dijelaskan satu per satu.',
                'Fokus panduan ini hanya pada kolom yang benar-benar terlihat di tabel.',
                'Area action juga dijelaskan supaya admin tahu kapan harus tambah atau edit metode.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.resources.methods.index') . '"]',
                'header' => '.fi-header',
                'actions' => '.fi-header-actions',
                'logo' => '.fi-ta thead th:nth-child(1)',
                'name' => '.fi-ta thead th:nth-child(2)',
                'code' => '.fi-ta thead th:nth-child(3)',
                'type' => '.fi-ta thead th:nth-child(4)',
                'gateway' => '.fi-ta thead th:nth-child(5)',
                'feePercent' => '.fi-ta thead th:nth-child(6)',
                'fixedFee' => '.fi-ta thead th:nth-child(7)',
                'minimum' => '.fi-ta thead th:nth-child(8)',
                'maximum' => '.fi-ta thead th:nth-child(9)',
                'status' => '.fi-ta thead th:nth-child(10)',
                'createdAt' => '.fi-ta thead th:nth-child(11)',
                'rowAction' => '.fi-ta tbody tr:first-child td:last-child a, .fi-ta tbody tr:first-child td:last-child button',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Payment Methods',
                    'description' => 'Gunakan menu ini untuk masuk ke daftar seluruh metode pembayaran yang tersedia di toko.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'header',
                    'title' => 'Ringkasan Halaman Payment',
                    'description' => 'Header halaman membantu admin memastikan bahwa perubahan yang dilakukan akan berdampak langsung ke checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'actions',
                    'title' => 'Aksi Tambah Metode',
                    'description' => 'Dari area ini admin bisa menambah metode baru atau memakai action yang tersedia untuk kebutuhan manajemen payment.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'logo',
                    'title' => 'Kolom Logo',
                    'description' => 'Kolom ini membantu admin mengenali metode pembayaran secara visual melalui logo atau ikon yang tampil di checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'name',
                    'title' => 'Kolom Nama Metode',
                    'description' => 'Nama metode dipakai sebagai label utama yang dibaca customer saat memilih pembayaran.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'code',
                    'title' => 'Kolom Kode',
                    'description' => 'Kode metode dipakai di sistem untuk pemetaan gateway, callback, dan identitas metode secara teknis.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'type',
                    'title' => 'Kolom Tipe',
                    'description' => 'Tipe membantu admin membedakan apakah metode ini bank transfer, e-wallet, QRIS, virtual account, atau convenience store.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'gateway',
                    'title' => 'Kolom Gateway',
                    'description' => 'Gateway menunjukkan provider pembayaran yang menangani metode tersebut, misalnya manual, Tripay, Tokopay, atau Paydisini.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'feePercent',
                    'title' => 'Kolom Fee Persen',
                    'description' => 'Bagian ini menunjukkan biaya persentase yang dibebankan ke metode pembayaran tersebut.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'fixedFee',
                    'title' => 'Kolom Fix Fee',
                    'description' => 'Fix fee dipakai untuk melihat biaya tetap per transaksi yang akan dikenakan selain biaya persentase.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'minimum',
                    'title' => 'Kolom Minimum',
                    'description' => 'Nilai minimum membantu admin memastikan metode ini hanya tersedia jika nominal transaksi memenuhi batas minimal.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'maximum',
                    'title' => 'Kolom Maximum',
                    'description' => 'Batas maksimum dipakai agar metode tidak muncul untuk transaksi yang melewati nominal tertentu.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'status',
                    'title' => 'Kolom Status',
                    'description' => 'Status menunjukkan apakah metode aktif dan bisa dipakai customer, atau sedang dinonaktifkan dari checkout.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'createdAt',
                    'title' => 'Kolom Dibuat',
                    'description' => 'Kolom tanggal pembuatan memudahkan admin melihat kapan metode ini pertama kali ditambahkan ke sistem.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'rowAction',
                    'title' => 'Action: Edit Metode',
                    'description' => 'Gunakan action pada tiap baris untuk membuka editor metode, lalu ubah fee, status, logo, atau aturan nominal sesuai kebutuhan.',
                    'placement' => 'left',
                ],
            ],
        ],
        'filament.admin.pages.settings' => [
            'guideBadge' => 'Panduan Settings Hub',
            'guideTitle' => 'Pilih submenu settings sesuai domain kerja',
            'guideDescription' => 'Halaman ini jadi pintu utama untuk konfigurasi website. Masuk ke submenu yang sesuai agar perubahan lebih fokus dan aman.',
            'guideHighlights' => [
                'Settings dipisah per area agar tidak membingungkan tim operasional.',
                'Setiap submenu menyimpan field whitelist miliknya sendiri.',
                'Gunakan kartu shortcut untuk masuk cepat ke section yang dibutuhkan.',
            ],
            'targets' => [
                'menu' => 'a[href="' . route('filament.admin.pages.settings') . '"]',
                'hub' => '[data-onboarding-target="settings-hub"]',
                'cards' => '[data-onboarding-target="settings-hub-cards"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'menu',
                    'title' => 'Menu Settings',
                    'description' => 'Klik menu ini untuk membuka pusat pengaturan website.',
                    'placement' => 'right',
                ],
                [
                    'targetKey' => 'hub',
                    'title' => 'Settings Hub',
                    'description' => 'Bagian ini menjelaskan bahwa pengaturan sekarang dipisah per domain agar lebih mudah dikelola.',
                    'placement' => 'bottom',
                ],
                [
                    'targetKey' => 'cards',
                    'title' => 'Shortcut Submenu',
                    'description' => 'Gunakan kartu submenu untuk masuk ke General, Branding, SEO, Payment, Providers, Notifications, atau Rewards.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.pages.settings.general' => [
            'guideBadge' => 'Settings: General',
            'guideTitle' => 'Kelola konfigurasi umum website',
            'guideDescription' => 'Submenu ini berisi informasi inti website, popup homepage, live sales, dan CAPTCHA login admin.',
            'guideHighlights' => [
                'Ubah identitas website dan prefix order dari satu tempat.',
                'Kontrol popup homepage serta toast transaksi.',
                'Kelola CAPTCHA admin secara terpisah.',
            ],
            'targets' => [
                'websiteInfo' => '[data-onboarding-target="settings-website-information"]',
                'homePopup' => '[data-onboarding-target="settings-homepage-popup"]',
                'captcha' => '[data-onboarding-target="settings-admin-captcha"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'websiteInfo',
                    'title' => 'Informasi Website',
                    'description' => 'Atur judul website, deskripsi, keyword, dan tema public aktif.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'homePopup',
                    'title' => 'Popup & Live Sales',
                    'description' => 'Aktif/nonaktifkan popup homepage dan live sales toast.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'captcha',
                    'title' => 'CAPTCHA Login Admin',
                    'description' => 'Kelola keamanan login admin melalui CAPTCHA dan bypass darurat.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Klik simpan setelah perubahan selesai dicek.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.pages.settings.branding' => [
            'guideBadge' => 'Settings: Branding',
            'guideTitle' => 'Atur identitas visual brand',
            'guideDescription' => 'Submenu ini dipakai untuk logo, warna utama, tema musiman, dan sosial media storefront.',
            'guideHighlights' => [
                'Logo header/footer/favicon dikelola terpusat.',
                'Tema musiman bisa dijadwalkan.',
                'Link sosial media selalu sinkron dengan storefront.',
            ],
            'targets' => [
                'branding' => '[data-onboarding-target="settings-branding"]',
                'seasonal' => '[data-onboarding-target="settings-seasonal-theme"]',
                'socialMedia' => '[data-onboarding-target="settings-social-media"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'branding',
                    'title' => 'Logo & Colors',
                    'description' => 'Ganti aset logo dan warna utama brand dari bagian ini.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'seasonal',
                    'title' => 'Seasonal Theme',
                    'description' => 'Aktifkan tema musiman, efek, serta jadwal tampil.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'socialMedia',
                    'title' => 'Social Media',
                    'description' => 'Isi URL WhatsApp, Instagram, TikTok, YouTube, dan Facebook.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Simpan supaya perubahan branding langsung diterapkan.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.pages.settings.seo-tracking' => [
            'guideBadge' => 'Settings: SEO & Tracking',
            'guideTitle' => 'Atur pelacakan dan crawling',
            'guideDescription' => 'Semua konfigurasi tracking analytics dan SEO robots/sitemap ada di submenu ini.',
            'guideHighlights' => [
                'Pisahkan tracking script dari konfigurasi visual.',
                'Validasi XML custom sitemap langsung dari panel.',
                'Kontrol robots.txt dan sitemap cache.',
            ],
            'targets' => [
                'analytics' => '[data-onboarding-target="settings-analytics-tracking"]',
                'seo' => '[data-onboarding-target="settings-seo"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'analytics',
                    'title' => 'Analytics & Tracking',
                    'description' => 'Atur GA4, Facebook Pixel, GTM ID, dan custom snippet.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'seo',
                    'title' => 'SEO Crawling',
                    'description' => 'Konfigurasi robots, sitemap mode, dan validasi file XML.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Simpan agar konfigurasi SEO dan tracking langsung aktif.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.pages.settings.payment-gateways' => [
            'guideBadge' => 'Settings: Payment Gateways',
            'guideTitle' => 'Kelola gateway dan akun pembayaran',
            'guideDescription' => 'Submenu ini berisi jalur deposit, credential gateway, serta akun payment manual.',
            'guideHighlights' => [
                'Semua credential payment dipusatkan di satu halaman.',
                'Akun e-wallet dan rekening bank dikelola bersama.',
                'Mengurangi risiko salah edit antar gateway.',
            ],
            'targets' => [
                'deposit' => '[data-onboarding-target="settings-deposit-configuration"]',
                'duitku' => '[data-onboarding-target="settings-duitku"]',
                'ewallet' => '[data-onboarding-target="settings-ewallet-accounts"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'deposit',
                    'title' => 'Deposit Configuration',
                    'description' => 'Pilih jalur gateway deposit utama yang dipakai sistem.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'duitku',
                    'title' => 'Credential Gateway',
                    'description' => 'Isi dan cek credential tiap gateway sesuai provider yang digunakan.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'ewallet',
                    'title' => 'Akun Pembayaran Manual',
                    'description' => 'Kelola nomor e-wallet dan rekening bank untuk channel manual.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Simpan setelah verifikasi credential dan akun pembayaran.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.pages.settings.providers-api' => [
            'guideBadge' => 'Settings: Providers & API',
            'guideTitle' => 'Kelola credential provider produk',
            'guideDescription' => 'Submenu ini khusus untuk API provider topup agar pemisahan dengan gateway pembayaran tetap jelas.',
            'guideHighlights' => [
                'Credential provider dipisah dari payment gateway.',
                'Memudahkan audit provider yang aktif.',
                'Lebih aman saat rotasi secret key.',
            ],
            'targets' => [
                'bangjeff' => '[data-onboarding-target="settings-bangjeff"]',
                'vipReseller' => '[data-onboarding-target="settings-vip-reseller"]',
                'apiGames' => '[data-onboarding-target="settings-api-games"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'bangjeff',
                    'title' => 'Provider Credentials',
                    'description' => 'Isi credential untuk BangJeff dan provider aktif lainnya.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'vipReseller',
                    'title' => 'VIP Reseller & Digiflazz',
                    'description' => 'Pastikan API ID, key, dan sign valid sebelum dipakai transaksi real.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'apiGames',
                    'title' => 'API Games',
                    'description' => 'Kelola Merchant ID dan Secret Key API Games pada section ini.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Simpan agar update credential provider diterapkan.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.pages.settings.notifications' => [
            'guideBadge' => 'Settings: Notifications',
            'guideTitle' => 'Atur channel notifikasi transaksi',
            'guideDescription' => 'Submenu ini memusatkan konfigurasi WhatsApp, SMTP, dan channel delivery invoice.',
            'guideHighlights' => [
                'Tes WhatsApp dan email langsung dari halaman ini.',
                'Atur channel invoice dan notifikasi affiliate.',
                'Pisahkan komunikasi dari konfigurasi provider.',
            ],
            'targets' => [
                'whatsapp' => '[data-onboarding-target="settings-whatsapp-configuration"]',
                'mail' => '[data-onboarding-target="settings-mail-configuration"]',
                'invoiceDelivery' => '[data-onboarding-target="settings-invoice-delivery"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'whatsapp',
                    'title' => 'WhatsApp Configuration',
                    'description' => 'Pilih provider WA aktif dan isi credential sesuai integrasi.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'mail',
                    'title' => 'Mail Configuration',
                    'description' => 'Atur SMTP host, port, akun, dan lakukan test email.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'invoiceDelivery',
                    'title' => 'Delivery Channels',
                    'description' => 'Tentukan channel notifikasi untuk invoice dan hasil review affiliate.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Simpan agar channel notifikasi langsung aktif.',
                    'placement' => 'top',
                ],
            ],
        ],
        'filament.admin.pages.settings.membership-rewards' => [
            'guideBadge' => 'Settings: Membership & Rewards',
            'guideTitle' => 'Kelola tier dan sistem poin',
            'guideDescription' => 'Submenu ini dipakai untuk markup tier, ambang kenaikan member, dan aturan poin user.',
            'guideHighlights' => [
                'Markup tier diatur terpisah untuk member/gold/platinum.',
                'Kenaikan level user berbasis transaksi sukses.',
                'Rasio poin dan batas pemakaian bisa dikontrol.',
            ],
            'targets' => [
                'tierMarkup' => '[data-onboarding-target="settings-tier-markup"]',
                'tierSystem' => '[data-onboarding-target="settings-tier-system"]',
                'pointSystem' => '[data-onboarding-target="settings-point-system"]',
                'save' => '[data-onboarding-target="settings-save"]',
            ],
            'steps' => [
                [
                    'targetKey' => 'tierMarkup',
                    'title' => 'Tier Markup',
                    'description' => 'Atur markup default untuk setiap level member.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'tierSystem',
                    'title' => 'Tier System',
                    'description' => 'Tentukan jumlah transaksi sukses untuk naik ke Gold/Platinum.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'pointSystem',
                    'title' => 'Point System',
                    'description' => 'Atur rasio poin, nilai rupiah poin, dan batas maksimal penggunaan.',
                    'placement' => 'left',
                ],
                [
                    'targetKey' => 'save',
                    'title' => 'Simpan Perubahan',
                    'description' => 'Simpan setelah aturan rewards final.',
                    'placement' => 'top',
                ],
            ],
        ],
    ];

    $guide = $pageGuides[$currentRouteName] ?? null;
@endphp

@if ($guide)
    @include('filament.admin.onboarding.partials.shell', [
        'guideBadge' => $guide['guideBadge'],
        'guideTitle' => $guide['guideTitle'],
        'guideDescription' => $guide['guideDescription'],
        'guideHighlights' => $guide['guideHighlights'],
        'onboardingScope' => $currentRouteName,
        'onboardingTargets' => $guide['targets'],
        'onboardingSteps' => $guide['steps'],
    ])
@endif
