/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.jsx',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'on-primary-fixed': '#351000',
                'on-background': '#e5e2e1',
                'on-secondary-container': '#b7b5b4',
                'primary-container': '#ff6b00',
                'secondary-fixed-dim': '#c8c6c5',
                'on-secondary-fixed-variant': '#474746',
                'on-primary': '#561f00',
                'inverse-primary': '#a04100',
                'on-surface-variant': '#e2bfb0',
                'surface-container-high': '#2a2a2a',
                'surface-container': '#201f1f',
                'on-tertiary-fixed': '#001f25',
                'tertiary-container': '#00a8c0',
                'secondary-container': '#474746',
                'outline-variant': '#5a4136',
                'on-tertiary-fixed-variant': '#004e5a',
                'error': '#ffb4ab',
                'on-primary-fixed-variant': '#7a3000',
                'inverse-surface': '#e5e2e1',
                'surface-bright': '#3a3939',
                'surface-container-low': '#1c1b1b',
                'primary-fixed': '#ffdbcc',
                'on-tertiary': '#00363f',
                'error-container': '#93000a',
                'on-secondary-fixed': '#1b1c1c',
                'tertiary-fixed-dim': '#00daf8',
                'tertiary': '#00daf8',
                'surface-variant': '#353534',
                'surface-container-highest': '#353534',
                'on-surface': '#e5e2e1',
                'secondary-fixed': '#e5e2e1',
                'outline': '#a98a7d',
                'secondary': '#c8c6c5',
                'background': '#131313',
                'on-tertiary-container': '#003740',
                'on-primary-container': '#572000',
                'surface-dim': '#131313',
                'primary': '#ffb693',
                'on-error-container': '#ffdad6',
                'surface-container-lowest': '#0e0e0e',
                'inverse-on-surface': '#313030',
                'primary-fixed-dim': '#ffb693',
                'tertiary-fixed': '#a5eeff',
                'surface': '#131313',
                'on-error': '#690005',
                'on-secondary': '#303030',
                'surface-tint': '#ffb693',
            },
            borderRadius: {
                'DEFAULT': '0.125rem',
                'lg': '0.25rem',
                'xl': '0.5rem',
                'full': '0.75rem',
            },
            spacing: {
                'lg': '24px',
                'sm': '8px',
                'margin-mobile': '16px',
                'gutter': '16px',
                'base': '4px',
                'margin-desktop': '32px',
                'xl': '40px',
                'md': '16px',
                'xs': '4px',
            },
            fontFamily: {
                'label-bold': ['JetBrains Mono', 'monospace'],
                'display-lg': ['Montserrat', 'sans-serif'],
                'body-sm': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'label-sm': ['JetBrains Mono', 'monospace'],
                'headline-lg-mobile': ['Montserrat', 'sans-serif'],
                'headline-lg': ['Montserrat', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'headline-md': ['Montserrat', 'sans-serif'],
            },
            fontSize: {
                'label-bold': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
                'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
                'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
                'label-sm': ['11px', { lineHeight: '1', fontWeight: '500' }],
                'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'headline-md': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
            },
        },
    },
    plugins: [],
};
