// @ts-check

/**
 * Sidebar eksplisit, bukan `autogenerated`.
 *
 * Alasan: urutan baca di dokumentasi API adalah bagian dari kontraknya
 * (konsep -> autentikasi -> endpoint -> webhook), sedangkan `autogenerated`
 * mengikuti urutan abjad nama file dan akan menyusun ulang dirinya sendiri
 * setiap kali ada file baru. Eksplisit = urutan tidak pernah berubah diam-diam.
 *
 * Aturan: MAKSIMAL 2 level (kategori -> halaman). Tidak ada kategori bersarang.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    'intro',

    {
      type: 'category',
      label: 'Pendahuluan',
      collapsed: false,
      items: [
        'pendahuluan/konsep-integrasi',
        'pendahuluan/base-url',
      ],
    },

    {
      type: 'category',
      label: 'Autentikasi',
      collapsed: false,
      items: [
        'autentikasi/bearer-token',
        'autentikasi/header-wajib',
        'autentikasi/error-codes',
      ],
    },

    {
      type: 'category',
      label: 'Keamanan',
      collapsed: false,
      items: [
        'keamanan/ip-whitelist',
      ],
    },

    {
      type: 'category',
      label: 'Endpoint',
      collapsed: false,
      items: [
        'endpoint/balance',
        'endpoint/category',
        'endpoint/variant',
        'endpoint/order',
        'endpoint/status-order',
      ],
    },

    {
      type: 'category',
      label: 'Sandbox',
      collapsed: false,
      items: [
        'sandbox/overview',
        'sandbox/simulate-status',
      ],
    },

    {
      type: 'category',
      label: 'Webhook',
      collapsed: false,
      items: [
        'webhook/overview',
        'webhook/payload',
        'webhook/signature-verification',
        'webhook/retry',
      ],
    },

    'rate-limit',

    {
      type: 'category',
      label: 'Manajemen',
      collapsed: false,
      items: [
        'manajemen/credentials',
        'manajemen/changelog',
      ],
    },
  ],
};

export default sidebars;
